### ISSUE TITLE
SegmentIDGenImpl的waitAndSleep方法中，sleep后是否应该使用continue

### ISSUE THREAD

**Issue by diaosou** [Meituan-Dianping/Leaf#1]
com.sankuai.inf.leaf.segment.SegmentIDGenImpl 的waitAndSleep方法，在 Thread.currentThread().sleep(10); 后的那个 break 是否应该改成 continue ？使用break直接跳出循环了

**Comment by Yaccc** [comment]
> com.sankuai.inf.leaf.segment.SegmentIDGenImpl 的waitAndSleep方法，在 Thread.currentThread().sleep(10); 后的那个 break 是否应该改成 continue ？使用break直接跳出循环了

就是为了让他自增到1000之后wait10ms 然后break掉哦

**Comment by diaosou** [comment]
> > com.sankuai.inf.leaf.segment.SegmentIDGenImpl 的waitAndSleep方法，在 Thread.currentThread().sleep(10); 后的那个 break 是否应该改成 continue ？使用break直接跳出循环了
> 
> 就是为了让他自增到1000之后wait10ms 然后break掉哦

waitAndSleep方法是“在当前buffer已消费完而另外那个buffer还未从数据库更新完成”的时候等待更新动作完成。现在的代码的逻辑是“连续检查10000次，如果仍未完成，则 wait 10ms后退出”，连续检查10000次的时间是很短的，几乎可以忽略不计，所以waitAndSleep的效果基本上就是wait 10ms，在这段时间内如果更新动作未完成，则会导致“两个Segment均未从DB中装载”的异常。不太理解这样处理的用意。
感觉此处是否使用“每 wait 10ms检查一次是否更新完成，如果检查了n次后仍未完成则退出”的方式来处理合适点？

**Comment by zztztt** [comment]
> 每 wait 10ms检查一次是否更新完成，如果检查了n次
是这样的，waitAndSleep已经是最后的一次短时间等待尝试了，其实前面触发DB更新的线程早就开始加载下个号段了，如果代码走到了waitAndSleep这个环节，相当于前面90%buffer的时间都没有从DB中把号段加载上来（这时候理论上已经是一个异常情况了，因为这部分时间已经是分钟级别了）。而这块waitAndSleep实际上就是一次最后尝试。
加入每次都等10ms，等N次，那么会有很多请求处理线程hang在这里

**Comment by zztztt** [comment]
> > > com.sankuai.inf.leaf.segment.SegmentIDGenImpl 的waitAndSleep方法，在 Thread.currentThread().sleep(10); 后的那个 break 是否应该改成 continue ？使用break直接跳出循环了
> > 
> > 
> > 就是为了让他自增到1000之后wait10ms 然后break掉哦
> 
> waitAndSleep方法是“在当前buffer已消费完而另外那个buffer还未从数据库更新完成”的时候等待更新动作完成。现在的代码的逻辑是“连续检查10000次，如果仍未完成，则 wait 10ms后退出”，连续检查10000次的时间是很短的，几乎可以忽略不计，所以waitAndSleep的效果基本上就是wait 10ms，在这段时间内如果更新动作未完成，则会导致“两个Segment均未从DB中装载”的异常。不太理解这样处理的用意。
> 感觉此处是否使用“每 wait 10ms检查一次是否更新完成，如果检查了n次后仍未完成则退出”的方式来处理合适点？

前面已经留了90%buffer消耗的时间来更新DB了（这部分时间已经是分钟级别的了），其实到了waitAndSleep已经可以算作是异常状态了，wait 10ms是最后的尝试了。如果每次wait 10ms，wait N次，那么可能导致很多线程hang在这里。

**Comment by Yaccc** [comment]
@diaosou 楼上正解了

**Comment by diaosou** [comment]
@zztztt @Yaccc 了解了，谢谢解答。

**Comment by islongfei** [comment]
mark

**Comment by good2luck** [comment]
mark
