### ISSUE TITLE
leaf.snowflake.port配置的作用是什么？

### ISSUE THREAD

**Issue by YuanPan** [Meituan-Dianping/Leaf#101]
leaf.snowflake.port的解释是：snowflake模式下的服务注册端口。但是我明白这个端口有什么作用，可以解释详细点吗？

**Comment by seustones** [comment]
建本地存workID的文件: workerID.properties

**Comment by NotFound9** [comment]
leaf.snowflake.port就是leaf项目的访问端口，例如你在一台服务器上部署了多个leaf服务，每个leaf服务的HTTP服务访问端口不一样，那么在使用snowflake模式生成ID时，每个leaf服务都会有一个唯一的workId进行区分，来防止id重复，这个workId就是个根据服务所在的服务器Ip+服务端口leaf.snowflake.port来唯一确定的，主要通过将ip:port以写入到zookeeper特定路径下，写入一个永久有序节点，会生成一个唯一的序列号，这个序列作为这个leaf服务的workId，以后再在这个ip的服务器上以这个端口启动leaf服务，会根据ip和端口去Zookeeper找到以前生成的对应的workId，进行使用。

**Comment by YuanPan** [comment]
> leaf.snowflake.port就是leaf项目的访问端口，例如你在一台服务器上部署了多个leaf服务，每个leaf服务的HTTP服务访问端口不一样，那么在使用snowflake模式生成ID时，每个leaf服务都会有一个唯一的workId进行区分，来防止id重复，这个workId就是个根据服务所在的服务器Ip+服务端口leaf.snowflake.port来唯一确定的，主要通过将ip:port以写入到zookeeper特定路径下，写入一个永久有序节点，会生成一个唯一的序列号，这个序列作为这个leaf服务的workId，以后再在这个ip的服务器上以这个端口启动leaf服务，会根据ip和端口去Zookeeper找到以前生成的对应的workId，进行使用。

谢谢，这么一说我明白了。
