### ISSUE TITLE
时间差过大，超过41位溢出，导致生成的id负数的问题

### ISSUE THREAD

**Issue by NotFound9** [Meituan-Dianping/Leaf#106]
因为Leaf框架是沿用snowflake的位数分配，
![image](https://user-images.githubusercontent.com/16741621/80939338-efacff80-8e0e-11ea-99d4-d90484f09248.png)

最大41位时间差+10位的workID+12位序列化，但是由于snowflake是强制要求第一位为符号位0，否则生成的id转换为十进制后会是复试，但是Leaf项目中没有对时间差进行校验，当时间戳过大或者自定义的twepoch设置不当过小，会导致计算得到的时间差过大，转化为2进制后超过41位，且第一位为1，会导致生成的long类型的id为负数，例如当timestamp = twepoch+2199023255552L时，
此时在生成id时，timestamp - twepoch会等于2199023255552，2199023255552转换为二进制后是1+41个0，此时生成的id由于符号位是1，id会是负数-9223372036854775793
```
 long id = ((timestamp - twepoch) << timestampLeftShift) | (workerId << workerIdShift) | sequence;
```
虽然这是很特殊的一种情况，但是我看百度uid-generator也考虑到了这种情况，代码中有对这种情况的判断，所以我觉得还是Leaf也有必要修复一下，所以我提了这个PR
https://github.com/Meituan-Dianping/Leaf/pull/105
对这个问题进行了修复，希望美团的朋友们有空可以看一看。

另外美团对于Leaf的介绍文章里面对于snowflake算法介绍用的配图存在错误，序列号的位数分配应该是12位，而不是10位，不然总位数不是63位。
![image](https://user-images.githubusercontent.com/16741621/80939461-46b2d480-8e0f-11ea-87fd-a8e9285d5e0d.png)

**Comment by zztztt** [comment]
文章中的书写问题应该修改过了，这部分的处理，我们看一下，感谢PR

**Comment by NotFound9** [comment]
@zztztt 感谢回复，我是看官网文章的配图好像是没有修改的，https://tech.meituan.com/2017/04/21/mt-leaf.html
另外我还提了一些其他的PR，可以一起看一下吗，希望可以为Leaf贡献代码，为开源做一点贡献，谢谢了！

**Comment by zztztt** [comment]
> @zztztt 感谢回复，我是看官网文章的配图好像是没有修改的，https://tech.meituan.com/2017/04/21/mt-leaf.html
> 另外我还提了一些其他的PR，可以一起看一下吗，希望可以为Leaf贡献代码，为开源做一点贡献，谢谢了！
收到，近期工作内部事情略多，我会抽空看下的，主要是测试部分，感谢贡献！

**Comment by NotFound9** [comment]
> > @zztztt 感谢回复，我是看官网文章的配图好像是没有修改的，https://tech.meituan.com/2017/04/21/mt-leaf.html
> > 另外我还提了一些其他的PR，可以一起看一下吗，希望可以为Leaf贡献代码，为开源做一点贡献，谢谢了！
> > 收到，近期工作内部事情略多，我会抽空看下的，主要是测试部分，感谢贡献！

好的，辛苦了，谢谢了
