### ISSUE TITLE
这个参数为啥要传false

### ISSUE THREAD

**Issue by yuyu414** [Meituan-Dianping/Leaf#109]
我想问一下 你这个类里面src/main/java/com/sankuai/inf/leaf/segment/dao/impl/IDAllocDaoImpl.java
![image](https://user-images.githubusercontent.com/25549434/83236593-5632fc80-a1c6-11ea-86f1-8210bdc05080.png)
你这俩个方法的openSession方法一个没传参数一个传值为false，为啥还要穿false呢，默认不就是false吗？

**Comment by zztztt** [comment]
应该是代码规范问题，我们看下哈
