### ISSUE TITLE
支持批量获取ID吗

### ISSUE THREAD

**Issue by youkandoit** [Meituan-Dianping/Leaf#11]
当需要批量插入记录时，循环调用获取ID的方式效率如何？
如果不支持批量获取ID，针对这种场景有什么建议吗？谢谢～

**Comment by nsspw** [comment]
同问；为了提高取号效率，不知道Leaf能否支持本地+远程模式：每次取一批号到本地，用完后再从远程获取一批，这样可以减少调用次数，不知道Leaf能否支持?

**Comment by zztztt** [comment]
> 同问；为了提高取号效率，不知道Leaf能否支持本地+远程模式：每次取一批号到本地，用完后再从远程获取一批，这样可以减少调用次数，不知道Leaf能否支持?

公司内部版本是有批量拉取逻辑的，但是我们一般都不建议这么用（公司内部的拉取逻辑最多只会拉取一个buffer的大小的号段）。因为本身Leaf双buffer的机制，导致批量拉取过大的化，会卡在DB更新时间上面。
这种情况建议，可以把Leaf直接嵌入到应用服务里。

**Comment by helpta** [comment]
'Leaf直接嵌入到应用服务' 还怎么做统一的id生成中心？  我也觉得是有这种批量获取场景的。我有十条记录要入库，一下拿十个就可以了，而不用循环拿十次。这种性能不会有什么瓶颈，如果并发不高，就跟普通的获取没啥差别，如果并发高，设计好相应步长就可以了。

**Comment by yudeng101** [comment]
看来只能自己实现了

**Comment by leechliao** [comment]
mark
