### ISSUE TITLE
我看了一些代码，有个问题

### ISSUE THREAD

**Issue by yuyu414** [Meituan-Dianping/Leaf#111]
这个不是支持动态的的扩大或者减小步长，但是我看只是在内存中增加了，不会把db的步长做增减？是什么考量呢？

**Comment by NotFound9** [comment]
一方面可能是为了便于管理和维护，一方面是因为每个Leaf服务消耗分布式ID的速度可能不一样（由于负载均衡，网速等原因等导致的），直接改DB的步长，可能会同时导致其他服务获取ID的步长。

假如有多条Leaf服务来生成分布式ID，假如负载均衡给某个Leaf服务A分配的请求少，这样分布式ID发放得也比较少，消耗也比较慢，其他Leaf服务B消耗得比较快，如果服务B在改完内存中的步长后，去修改DB中的步长的话，会导致Leaf服务A每次去DB中取到的id过多，消耗不完。如果只是服务B只是修改自己内存中的步长，那么就不会影响其他服务获取ID的步长。

**Comment by yuyu414** [comment]
嗯，好的
我看到代码里是使用的是mysql的事务来处理，而不是spring的事务管理器，看代码实现并压测了一番，貌似不会产生启动多个服务来更新数据库的maxId，并发导致Id重复的问题

**Comment by NotFound9** [comment]
不是并发的问题，是可能每个Leaf服务消耗ID的速度不同（例如nginx进行请求分配，假设给某个Leaf分配的请求较多，就会造成这个Leaf服务消耗的id过快），或者在某个时间点，有大量的获取分布式ID的需求，如果改了数据库里面的步长，并且其他正在运行的Leaf服务检测到并且更新内存中步长的话，可能其他运行的Leaf服务消耗速度没有那么快，就会造成id的浪费，以及过了这个时间点，需求少了，又需要改回来。

**Comment by NotFound9** [comment]
而且根据目前的动态调整的算法来看，步长调整还是相对比较频繁的，白天跟晚上的id生成需求量肯定是差别特别大，以及高峰期跟平稳时期id生成需求量也不同，这么看的话，每天都会改很多次步长，那样同步到DB可能意义不大了

**Comment by yuyu414** [comment]
这个我明白了 我不是在问这个

**Comment by yuyu414** [comment]
不会产生启动多个服务来更新数据库的maxId，不会并发导致Id重复的问题 ，是基于数据库的锁来做的是吗？

**Comment by NotFound9** [comment]
是的，更新maxId的操作，查询maxId的操作是在同一个innodb事务里面进行，执行更新操作时需要先获得这个数据行的记录锁（行锁中的record lock），调用commit()方法事务提交后，其他更新操作的事务才能获取到锁进行更新。你要是不太了解MySQL的事务，可以看看我最近写的一篇文章[【大厂面试03期】讲讲一条MySQL更新语句是怎么执行的？](https://mp.weixin.qq.com/s/pNe1vdTT24oEoJS_zs-5jQ)

![image](https://user-images.githubusercontent.com/16741621/83858463-20a28c00-a74f-11ea-897e-74ced05539d1.png)

**Comment by yuyu414** [comment]
我知道，就是确认一下
