### ISSUE TITLE
原生long直接返回ID,比Result结构包装再返回,效率要高很多.

### ISSUE THREAD

**Issue by automvc** [Meituan-Dianping/Leaf#114]

**Comment by NotFound9** [comment]
直接返回ID，如果生成的是错误的ID，并且是正数的话，调用方无法区分获得的ID是有效的，还是错误的ID，所以才会需要status进行区分

**Comment by automvc** [comment]
> 直接返回ID，如果生成的是错误的ID，并且是正数的话，调用方无法区分获得的ID是有效的，还是错误的ID，所以才会需要status进行区分

你说的情形,可以举些例子吗,      异常的时候不可以都赋负数吗?

**Comment by NotFound9** [comment]
使用Result结构更加方便扩展，后续可以增加meesage字段来包含具体的报错提示，方便调用方了解具体的报错信息
