### ISSUE TITLE
让Segment模式生成的ID不连续，保证信息安全性

### ISSUE THREAD

**Issue by NotFound9** [Meituan-Dianping/Leaf#119]
我提了一个[PR#118](https://github.com/Meituan-Dianping/Leaf/pull/118)，让让Segment模式生成的ID不连续，保证信息安全性。

在[Leaf的官方介绍文章](https://tech.meituan.com/2017/04/21/mt-leaf.html)中曾经提到分布式ID应该保证信息安全性，

>4.信息安全：如果ID是连续的，恶意用户的扒取工作就非常容易做了，直接按照顺序下载指定URL即可；如果是订单号就更危险了，竞对可以直接知道我们一天的单量。所以在一些应用场景下，会需要ID无规则、不规则。

![image](https://user-images.githubusercontent.com/16741621/84752324-30905a80-aff0-11ea-8bb4-2fc0b781cc3a.png)
![image](https://user-images.githubusercontent.com/16741621/84753580-c2e52e00-aff1-11ea-9e7f-389c962ed54a.png)

让ID不连续，否则容易被恶意爬取和泄露单量，目前使用snowflake模式生成ID时是有取随机数相关的逻辑来保证ID不连续的，但是如果是Leaf-segment数据库方案来生成ID，每次从数据库取完ID，都是存储在内存中，发放给业务项目，所以运行期间，使用的ID都是连续的，竞争对手很容易通过在两天中午12点分别下单，通过订单id号相减就能大致计算出公司一天的订单量。如果我们在每次从数据库取一个分段的ID时，计算一个随机数，丢弃掉随机数数量的ID，这样就可以保证ID不连续，保证Leaf-segment数据库方案来保证生成ID的安全性。

源代码：SegmentIDGenImpl中updateSegmentFromDb()方法中计算当前ID分段最小值
```java
long value = leafAlloc.getMaxId() - buffer.getStep();
```
修改后的代码
```java
 int bound = buffer.getStep()/20;//随机值最大取值为5%的Step，主要考虑到buffer中id使用量超过10%就会触发另一个buffer的更新，所以我们取的随机值的最大值小于10%会好一些，不然一开始就触发更新了。
int randomValue = RANDOM.nextInt(bound);//生成随机值
long value = leafAlloc.getMaxId() - buffer.getStep() + randomValue;//丢弃随机值数量的id，让id不连续，保证id安全性
   ```

**Comment by Yaccc** [comment]
分布式系统里用户ID生成有什么好的方法和规则能满足“唯一、尽量短、不能直接看出规则”这几个条件? - 谢照东的回答 - 知乎
https://www.zhihu.com/question/20180484/answer/172956173 

你可以在拿到id之后对id做位移\置换等操作，此类计算类型耗费cpu，且不同业务有自己不同的算法，建议在客户端拿到唯一id之后自行实现

**Comment by NotFound9** [comment]
好的，收到，谢谢大佬指教，确实是可以通过自定义一些算法或规则，针对原ID计算得到一个新ID，并且是趋势递增的
