### ISSUE TITLE
[咨询] Snowflake Id 序列不区分 key 的设计考虑

### ISSUE THREAD

**Issue by xiaozongyang** [Meituan-Dianping/Leaf#127]
Hi Leaf Community,

初来乍到，多多包涵，有个问题想请教下。

当前 master (revision: `86a6441d263497b9f9ee321de13422b9c63f0c06`) 中，`SnowflakeIDGenImpl#get` 方法声明如下：
```java
public synchronized Result get(String key) 
```
从源码中得出两个实现细节：
1. `SnowflakeIDGenImpl#get` 方法是加了对象级别的可重入锁
2. 参数 `key` 在 `get`方法的实现里没用到
3. `SnowFlakeIdGenImpl` 在 `SnowfalkeService` 是单例，`SnowflakeSerivce` 也是单例
4. 由 1 2 3 可以知道，对于某个 Leaf-Server 实例，所有到 `/api/snowflake/get/{key}` 的请求，共享同一个 `SnowflakeIdGenImpl`，即属于同一个 ID 序列，可能存在两个风险
     1. 不同的 key 共享同一个 ID 序列，导致 `sequence` 用的比较快，可能有在一个毫秒内耗完 `sequence` 的风险
     2. 在 `SnowflakeIDGenImpl#get` 方法上做同步，会降低并发性能，这里可能会成为瓶颈

基于上述理解，有几个问题想请教下：
1. 对于 leaf server snowflake，有没有参考数据，单机到多少 qps 是个比较安全的值
2. 在 `SnowflakeIDGenImpl#get` 方法上做同步，有什么设计上的考虑，如果改成在 `key` 级别做同步会有什么坑，潜在的问题可能是 `key` 如何维护

**Comment by zztztt** [comment]
你好，最初版本是没有做key区分的，这块确实需要区分，近期会更新开源版本fix

**Comment by xiaozongyang** [comment]
有什么计划吗？或者有啥大方向上的方案，乐意参与贡献代码或者讨论 :)
