### ISSUE TITLE
多台机器并发读取数据库拿到相同maxId的问题

### ISSUE THREAD

**Issue by wushengtao** [Meituan-Dianping/Leaf#129]
多台机器部署了发号器，初始化同时会读取数据库，拿到的maxId记录不是一样的么，多台机器的本地号段不是重复了么？
加分布式锁or select for update锁单行记录？

**Comment by programming-pupil** [comment]
你的观点是错误的，首先他们是在一个事务里的，其次update会上锁的，不会重复maxId的。源码如下图：
![image](https://user-images.githubusercontent.com/22268180/87907598-7df06380-ca97-11ea-9738-9eddb9a4cebf.png)
![image](https://user-images.githubusercontent.com/22268180/87907627-89438f00-ca97-11ea-8043-8bf6282a4b04.png)

不过我有个疑问就是为嘛不给tag加唯一索引呢？这样表锁就升级为行锁了，不是更好一点吗？

**Comment by programming-pupil** [comment]
> 你的观点是错误的，首先他们是在一个事务里的，其次update会上锁的，不会重复maxId的。源码如下图：
> ![image](https://user-images.githubusercontent.com/22268180/87907598-7df06380-ca97-11ea-9738-9eddb9a4cebf.png)
> ![image](https://user-images.githubusercontent.com/22268180/87907627-89438f00-ca97-11ea-8043-8bf6282a4b04.png)
> 
> 不过我有个疑问就是为嘛不给tag加唯一索引呢？这样表锁就升级为行锁了，不是更好一点吗？

这里说的加索引请忽略，刚看到biz_tag是主键，所以是锁行的，不存在锁表的情况。
