### ISSUE TITLE
交流一下

### ISSUE THREAD

**Issue by yangfanchuhai** [Meituan-Dianping/Leaf#13]
昨天拜读了一下你的源码，发现在snowflake中，有可能存在内存可见性问题而有一定概率导致重复
![image](https://user-images.githubusercontent.com/11494672/54248181-a482be00-4576-11e9-9941-2cfa730d5e6c.png)
如果两个线程同时一秒内执行，1处导致重复的概率还是有的

**Comment by yangfanchuhai** [comment]
如果两个线程在同一ms内执行，但是对于各自的++操作不可见，会导致重复

**Comment by a-voyager** [comment]
只有这一个方法对 sequece 写入，而这个方法有 synchronized，所以不存在问题吧？

**Comment by yangfanchuhai** [comment]
没看到上面那个synchronized，不好意思，没看仔细。
