### ISSUE TITLE
打jar包有问题

### ISSUE THREAD

**Issue by TonyEasy** [Meituan-Dianping/Leaf#14]
无法直接运行所打的jar包

**Comment by zztztt** [comment]
辛苦发下异常栈信息

**Comment by zztztt** [comment]
> 无法直接运行所打的jar包

辛苦发下异常栈信息

**Comment by TonyEasy** [comment]
提示leaf.jar中没有主清单属性

**Comment by TonyEasy** [comment]
![0725708C-C896-4A1D-8D38-0910CC3A3DCE](https://user-images.githubusercontent.com/6257818/54262018-2b03c380-45a8-11e9-8823-11519c700cf7.png)

**Comment by zztztt** [comment]
启动方式见：leaf-server目录下的deploy/run.sh脚本
