### ISSUE TITLE
号段模式有些id被丢弃(segment切换)

### ISSUE THREAD

**Issue by JonahYan** [Meituan-Dianping/Leaf#15]
发现一个问题想请教：
我DB设置的step的步长为2000，消费了27个id，然后重启应用发现，
id不是从28开始，而是直接从2001开始， （2001-27）个id被丢弃，
丢弃掉了前一个segment剩余没有用到的id。

**Comment by zztztt** [comment]
> 发现一个问题想请教：
> 我DB设置的step的步长为2000，消费了27个id，然后重启应用发现，
> id不是从28开始，而是直接从2001开始， （2001-27）个id被丢弃，
> 丢弃掉了前一个segment剩余没有用到的id。

是的目前这个是正常逻辑，内存缓存的号段，如果没用完，服务重启是会丢弃掉的。后面开源版本，我们会将内存的未用完的号段归档到本地文件，重启的时候先使用文件中剩余的数据。
不过公司内部因为流量大和处于一些异常处理的角度，还是选择了在服务重启的时候丢弃这部分内存号段。
