### ISSUE TITLE
关于Leaf-snowflake方案生成ID数量的问题

### ISSUE THREAD

**Issue by cqdengdeng** [Meituan-Dianping/Leaf#158]
已经部署了Leaf并在实际中使用，由于时间紧没看源码直接部署，采用的是Leaf-snowflake方案生成19位的唯一ID。
现有一个困惑，近2个月时间，ID的前三位由最开始时的130已到目前的132了，如果用完了会自动递增位数吗？比如升为20位ID......

**Comment by zztztt** [comment]
long型数据最大应该就 19位，够用几十年，如果真的到了最大值，会更新成最小值
