### ISSUE TITLE
号段模式下,为什么在updateSegmentFromDb代码里,必须先设置value,再设置max

### ISSUE THREAD

**Issue by 1314cc** [Meituan-Dianping/Leaf#16]
你好,在 SegmentIDGenImpl.class 中, updateSegmentFromDb 方法里, 有一句注释, " // must set value before set max ",请问这里这样做是如何考虑的. 谢谢.

**Comment by 1314cc** [comment]
![must set value before set max ](https://user-images.githubusercontent.com/5126487/54412567-2e28bc00-472e-11e9-9f9f-4330df53f937.jpg)

**Comment by 1314cc** [comment]
🤔🤔🤔

**Comment by miaogr86** [comment]
都是单线程更新的，顺序应该没关系吧

**Comment by miaogr86** [comment]
![image](https://user-images.githubusercontent.com/5835603/54685770-99b9c180-4b52-11e9-8b86-c1df553f90bb.png)
这里是不是单线程池都可以的？

**Comment by 1314cc** [comment]
这个时候号段还没有Ready. @miaogr86

**Comment by zztztt** [comment]
> 这个时候号段还没有Ready. @miaogr86

是第一版本没有双buffer结构的时候留下的注释，主要是为了保证value优先可见不出现问题，下个版本会更正。
