### ISSUE TITLE
snowflake模式下，如果某一毫秒内分配的数目已经超过了4096时，会分配重复的id？

### ISSUE THREAD

**Issue by YDDMAX** [Meituan-Dianping/Leaf#162]
![image](https://user-images.githubusercontent.com/9697391/111120713-ae48bd00-85a6-11eb-9fbe-4a8948a55f8b.png)
zhe'duan
这段代码的实现会造成id重复吧？

**Comment by zacharyzhu096** [comment]
这种情况是不会出现的，掩码设置为：0000...1111111111，当时间戳相等的时候，当sequence值为00000...1000000000000的时候（即2048），这一毫秒的sequence值不可以继续使用，那么准备使用下一秒的sequence的值。所以他们才设置下一毫秒初始sequence的值，timestamp取下一毫秒的值。
