### ISSUE TITLE
snowflake模式, 为什么每ms第一个取随机数? 

### ISSUE THREAD

**Issue by GoldArowana** [Meituan-Dianping/Leaf#169]
snowflake模式下, 我看到每ms的第一个id 都会用rand(100) 来取随机数, 请问一下这样做得具体意义是什么呀？

**Comment by zztztt** [comment]
主要为了随机性，很多业务场景会使用后两位做分库分表的sharding key，如果每ms都取第一个id会使得低频场景下尾数都是00
