### ISSUE TITLE
也开源个springcloud版本的吧。

### ISSUE THREAD

**Issue by lyyncw** [Meituan-Dianping/Leaf#17]
也开源个springcloud版本的吧。

**Comment by zztztt** [comment]
> 也开源个springcloud版本的吧。

可以直接将leaf-core包嵌入进去即可。后面我们会考虑提供

**Comment by lyyncw** [comment]
嗯，多谢美团的开源分享。
我也是用到了阿里的Druid，它有springBoot也有springCloud版本的，包括携程apollo等，也有SpringCloud版本的。所以，如果咱们直接开源一份springCloud版本的话，其他使用springCloud微服务框架的同学，只需稍加修改即可使用。



lyyncw@sina.com
 
发件人： 张志桐
发送时间： 2019-03-15 17:39
收件人： Meituan-Dianping/Leaf
抄送： lyyncw; Author
主题： Re: [Meituan-Dianping/Leaf] 也开源个springcloud版本的吧。 (#17)
也开源个springcloud版本的吧。
可以直接将leaf-core包嵌入进去即可。后面我们会考虑提供
