### ISSUE TITLE
Preconditions类找不到，你的pom文件里面没有找到相关的包引用？是不是缺 包

### ISSUE THREAD

**Issue by JKAK47** [Meituan-Dianping/Leaf#2]
import com.google.common.base.Preconditions;

```xml
 <dependency>
                <groupId>com.google.guava</groupId>
                <artifactId>guava</artifactId>
                <version>23.0</version>
 </dependency>
```

**Comment by zztztt** [comment]
在guava包里， 是通过curator 引入的：
[INFO] +- org.apache.curator:curator-recipes:jar:2.6.0:compile
[INFO] |  +- org.apache.curator:curator-framework:jar:2.6.0:compile
[INFO] |  |  \- org.apache.curator:curator-client:jar:2.6.0:compile
[INFO] |  +- org.apache.zookeeper:zookeeper:jar:3.4.6:compile
[INFO] |  |  +- jline:jline:jar:0.9.94:compile
[INFO] |  |  \- io.netty:netty:jar:3.7.0.Final:compile
[INFO] |  \- com.google.guava:guava:jar:16.0.1:compile
