### ISSUE TITLE
关于注册到zk的key

### ISSUE THREAD

**Issue by acseed** [Meituan-Dianping/Leaf#21]
我司用的是docker发布， 每次发布后容器的ip都不一样， 如果拿ip注册到zookeeper,是不是会有问题， 本地文件缓存的workerId的意义就不是很大了， 你们有遇到这种情况吗？ 据我了解， 美团也是容器发布的， 你们的ip是不变的是吗

**Comment by mawenjian** [comment]
注册到ZK，本质上是在ZK中“排队”，拿“排队序号”作为自己的workerid，所有的网络抖动（包括但不限于更换IP）都会导致重新注册到ZK，进而workerid发生变更。
