### ISSUE TITLE
SegmentIDGenImpl 中 getIdFromSegmentBuffer 方法的一些疑惑

### ISSUE THREAD

**Issue by JackmanGo** [Meituan-Dianping/Leaf#23]
getIdFromSegmentBuffer() 在调用waitAndSleep()方法前currentSegment获取正确的value已经失败，在调用waitAndSleep()等待nextSegment完成对接DB的更新操作（如有必要）。
waitAndSleep()方法返回后，又对当前currentSegment尝试获取value。如果失败，则切换segment，下次循环中再次获取value

waitAndSlee()前后都对同一segment进行对获取value操作。这是有什么特殊含义在里面吗？

**Comment by 1314cc** [comment]
考虑在多线程情况下,当前Segment可能已经被调换了.直接进行一次获取value的操作,可以提高id下发的速度(没必要再走一次循环),并且防止出错(在交换Segment前进行一次检查). 我是这样想的. [meituan-leaf-1](https://www.blackchen.site/2019/03/18/meituan-leaf-1/) @JackmanGo
