### ISSUE TITLE
能够根据不同的业务模块生成一个业务段的id吗？？

### ISSUE THREAD

**Issue by YangGuang001** [Meituan-Dianping/Leaf#25]

**Comment by thelight1** [comment]
leaf是以biz_tag为维度的，保证对于单个biz_tag，获取id是唯一的。
【根据不同的业务模块生成一个业务段的id】是指保证业务模块内部id唯一？
是的话，为不同的业务模块使用不同的tag即可。

**Comment by YangGuang001** [comment]
tks，明白了。
