### ISSUE TITLE
关于snowflake的workerId

### ISSUE THREAD

**Issue by a252937166** [Meituan-Dianping/Leaf#26]
拜读了一下源码，目前workerI都是根据zk排队序号生成，大多时候为0。
这样的话根据workerId，也就不能反推出申请业务，在SnowflakeIDGenImpl的get方法中，参数key没有使用途径。
我建议workerId，其实可以由key的规则生成，这样workerId不是更有意义吗

**Comment by thelight1** [comment]
你理解有误。
1. workerId并不是大多数为0。
2.workerId不应该和key绑定。
------------------------------------
1）关于workerId
snowflake算法由3部分组成，timestamp+workerId+sequenceId。
为保证部署多台服务时，得到的id是唯一的，workerId必须是唯一的。
leaf中workerId是使用zk顺序节点的序号来保证唯一。
2）关于参数key没有用到
snowflake生成id并不依赖key，但为了管理和审计业务申请的key（也便于排查问题），要求调用方调用时传入key参数

**Comment by jakeslee** [comment]
@thelight1 在容器中部署，每次启动 IP 都是不相同的，用 zk 顺序号最终很快会超过 10 bits，这种情况如何规避？

**Comment by thelight1** [comment]
每次启动ip都不同，的确会存在上述问题。在美团内部也是使用的容器，重启后ip不会换。
