### ISSUE TITLE
生成短号

### ISSUE THREAD

**Issue by devxiaosong** [Meituan-Dianping/Leaf#27]
某些情况下ID号会作为参数的一部分编在二维码里，所以希望ID号能短一些。

我的想法是使用36进制进行标识。（0~9 A~Z）

是否可以实现一下。

**Comment by mawenjian** [comment]
进制转换，这么简单的需求，自己写个函数转换一下就行了呗。

**Comment by zztztt** [comment]
Leaf 号段模式转成32位，不过理论上也存在了重复风险，毕竟数据集小了
