### ISSUE TITLE
SegmentIDGenImpl中waitAndSleep方法可能存在code hoisting问题

### ISSUE THREAD

**Issue by single-wolf** [Meituan-Dianping/Leaf#30]
`

    private void waitAndSleep(SegmentBuffer buffer) {
        int roll = 0;
        while (buffer.getThreadRunning().get()) { //此处会引发code hoisting造成死循环，建议使用必要的同步实现
            roll += 1;
            if(roll > 10000) {
                try {
                    Thread.currentThread().sleep(10);
                    break;
                } catch (InterruptedException e) {
                    logger.warn("Thread {} Interrupted",Thread.currentThread().getName());
                    break;
                }
            }
        }
    }
`
测试样例

`

    public static void main(String[] args) throws InterruptedException, NoSuchMethodException {
        SegmentIDGenImpl segmentIDGen = new SegmentIDGenImpl();
        final SegmentBuffer buffer = new SegmentBuffer();
        Method waitAndSleepMethod = segmentIDGen.getClass().getDeclaredMethod("waitAndSleep", SegmentBuffer.class);
        new Thread(() -> {
            try {
                waitAndSleepMethod.setAccessible(true);
                waitAndSleepMethod.invoke(segmentIDGen, buffer);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }).start();
        System.out.println(System.nanoTime() + " main thread start sleep");
        Thread.sleep(1000);
        System.out.println(System.nanoTime() + " main thread wake up");
        buffer.getThreadRunning().compareAndSet(false, true); //set value of threadRunning to true
        System.out.println(System.nanoTime() + " main thread - " +
                "the current value of threadRunning : " + buffer.getThreadRunning().get());
    }
`

**Comment by single-wolf** [comment]
抱歉，测试样例里代码**逻辑有误**，所以一直 while 循环 :-(  ，并不是code hoisting问题
不过是否可以考虑用 CountDownLatch.await(timeout) down() 来实现线程间等待   
见pull request #31

**Comment by zztztt** [comment]
收到，我们review一下哈
