### ISSUE TITLE
当步长设置过小的时候，程序会报错

### ISSUE THREAD

**Issue by fliu721** [Meituan-Dianping/Leaf#35]
当步长设置为50。然后运行`SegmentIDGenImplTest`中的测试方法，循环5000次，就会报错：
`Both two segments in SegmentBuffer{key='leaf-segment-test', segments=[Segment(value:53,max:51,step:50), Segment(value:103,max:101,step:50)], currentPos=1, nextReady=false, initOk=true, threadRunning=true, step=50, minStep=50, updateTimestamp=1556434867190} are not ready!`

从错误信息来看，`threadRunning=true`表示当前`buffer`正在填充数据，但是获取`nextID`的逻辑并没有等待数据填充完，就尝试获取导致报错

**Comment by fliu721** [comment]
`waitAndSleep `这个方法去掉`Thread.currentThread().sleep(10);`后面的`break;`就不会有上述错误。
```java
private void waitAndSleep (SegmentBuffer buffer) {
        int roll = 0;
        while (buffer.getThreadRunning().get()) {
            roll += 1;
            if (roll > 10000) {
                try {
                    Thread.currentThread().sleep(10);
                    //break;
                } catch (InterruptedException e) {
                    logger.warn("Thread {} Interrupted", Thread.currentThread().getName());
                    break;
                }
            }
        }
    }
```

注释掉

**Comment by caoenergy** [comment]
是个bug

**Comment by zztztt** [comment]
首先步长小的话，就没必要通过leaf了，我们内部规定最小的step 也得是1k。另外这块仅是做最后的补救，也就是说，如果第一个buffer用完了，第二个没好的话，我们会尝试等一小段时间，如果还没好的话就放弃等待了。而不是一直陷入循环。否则DB宕机的话会一直夯住请求，进而导致cpu和线程数飙高

**Comment by leechliao** [comment]
> 首先步长小的话，就没必要通过leaf了，我们内部规定最小的step 也得是1k。

这个解释不合理，也比较强盗。fliu721反映的是个bug问题，不是使用方式问题。
