### ISSUE TITLE
snowflake 模式的疑问

### ISSUE THREAD

**Issue by tuser4198** [Meituan-Dianping/Leaf#39]
1.snowflake 模式新的毫秒数时random的考虑。
2.snowflake 模式生成的id是不定长的吧？定长的话有什么方案建议么？

**Comment by zztztt** [comment]
1. 主要是出于BD分表均匀考虑
2. 修改生成位数的策略可以搞定的

**Comment by zoujs** [comment]
@zztztt 你好，BD分表均匀是指？

**Comment by MrSorrow** [comment]
@zoujs @zztztt 是不是DB分表，写错了

**Comment by zoujs** [comment]
> @zoujs @zztztt 是不是DB分表，写错了

还是不懂跟均匀有什么关系...

**Comment by MrSorrow** [comment]
> > @zoujs @zztztt 是不是DB分表，写错了
> 
> 还是不懂跟均匀有什么关系...

是否和分表策略有关？
