### ISSUE TITLE
号段模式是不是有部分id没有被应用到

### ISSUE THREAD

**Issue by mikefreemanNice** [Meituan-Dianping/Leaf#4]
https://github.com/Meituan-Dianping/Leaf/blob/61f53f8c000d48f479c2a3a609f2d9ee6049e1aa/leaf-core/src/main/java/com/sankuai/inf/leaf/segment/SegmentIDGenImpl.java#L237

这里我理解有一个问题
segment切换后，原来的号段没有到达maxId，这时转到新的segment，value值重新计算，会废弃掉前一个segment剩余没有用到的id。

**Comment by Yaccc** [comment]
@mikefreemanNice 只有当前号段用完之后，才会走到这一步
