### ISSUE TITLE
关于snowflake的启动流程中leaf_temporary临时节点相关疑问

### ISSUE THREAD

**Issue by MrSorrow** [Meituan-Dianping/Leaf#40]
[官方博客](https://tech.meituan.com/2017/04/21/mt-leaf.html)介绍snowflake模式下整个启动流程如下：
> 服务启动时首先检查自己是否写过ZooKeeper leaf_forever节点：
> 1. 若写过，则用自身系统时间与leaf_forever/${self}节点记录时间做比较，若小于leaf_forever/${self}时间则认为机器时间发生了大步长回拨，服务启动失败并报警。
> 2. 若未写过，证明是新服务节点，直接创建持久节点leaf_forever/${self}并写入自身系统时间，接下来综合对比其余Leaf节点的系统时间来判断自身系统时间是否准确，具体做法是取leaf_temporary下的所有临时节点(所有运行中的Leaf-snowflake节点)的服务IP：Port，然后通过RPC请求得到所有节点的系统时间，计算sum(time)/nodeSize。
> 3. 若abs( 系统时间-sum(time)/nodeSize ) < 阈值，认为当前系统时间准确，正常启动服务，同时写临时节点leaf_temporary/${self} 维持租约。
> 4. 否则认为本机系统时间发生大步长偏移，启动失败并报警。
> 5. 每隔一段时间(3s)上报自身系统时间写入leaf_forever/${self}。

请问有关第2步、第3步临时节点leaf_temporary的相关逻辑，源码中好像没有，是否是版本更新摒弃了这一部分逻辑。

**Comment by thelight1** [comment]
2,3步逻辑需要引入RPC框架，leaf在开源时，将相关的代码给去掉了。@MrSorrow

**Comment by horsen689** [comment]
> 2,3步逻辑需要引入RPC框架，leaf在开源时，将相关的代码给去掉了。@MrSorrow

您好，请问一下，少了RPC访问做平均值效验的过程，会产生什么影响？

**Comment by thelight1** [comment]
做平均值校验是为了应对时钟回拨问题。目前还没有发现启动失败并报警的情况。
