### ISSUE TITLE
请问一下怎么配置生成的id的长度呢？

### ISSUE THREAD

**Issue by iLikeEateFruit** [Meituan-Dianping/Leaf#46]
请问关于雪花算法，我看了一下默认生成的是19位的id，请问怎么控制id生成的长度呢？旧有系统有16位id的，也有22位id的，都想用id自动生成

**Comment by thelight1** [comment]
1）snowflake算法中有个初始基准时间戳，基于当前leaf中设置的初始时间戳，生成的id都是19位(long型)的。
2）如何控制id生成长度？这个只能自己处理了。
snowflake算法生成的id是long型的，long型转为字符串的话，最大为19位（Long.MAX_VALUE)。
你说的16位、22位应该是字符串类型的id吧。对于16位的，可以用号段模式的，初始max_id设为1,000,000,000,000,000；对于22位的，也可以借助号段模式，比如填充0达到22位。当然借助leaf生成id，需要考虑是否与原来的id会发生重复。还要注意的是，snowflake生成的id截取后是无法保证唯一性的。

**Comment by iLikeEateFruit** [comment]
恩，谢谢了
