### ISSUE TITLE
如何规避「伪共享」FalseSharing问题

### ISSUE THREAD

**Issue by miniFrank** [Meituan-Dianping/Leaf#47]
如题

**Comment by thelight1** [comment]
如何规避伪共享问题是指？

**Comment by Yaccc** [comment]
> 如题

目前leaf没有考虑到伪共享问题，最初有讨论，
目前java8 @content 注解可以解决伪共享，但是低版本还是需要用其他基本类型填充对象，可以考虑提个PR 哈哈哈 @miniFrank

**Comment by miniFrank** [comment]
> > 如题
> 
> 目前leaf没有考虑到伪共享问题，最初有讨论，
> 目前java8 @content 注解可以解决伪共享，但是低版本还是需要用其他基本类型填充对象，可以考虑提个PR 哈哈哈 @miniFrank

嗯，好的，我也打算用你们的来做分布式ID服务（PS：20天过去了）

**Comment by gang-yu** [comment]
baidu的id generater有类似处理，可以看看有无参考价值

**Comment by thelight1** [comment]
> baidu的id generater有类似处理，可以看看有无参考价值

感谢反馈，研究过baidu的id生成器，它们是因为引入了ringbuffer，维护head、tail两个索引，所有有伪共享问题。
