### ISSUE TITLE
segment模式极端情况

### ISSUE THREAD

**Issue by clark07** [Meituan-Dianping/Leaf#48]
考虑极端情况
假设step=10,当有21个请求同时进来  
1.编号1-10通过bufferA返回  第二个请求去load bufferB数据
2.编号11-21进入waitAndSleep等待
3.bufferB加载完成 编号11-20通过bufferB返回  编号21将抛异常

![image](https://user-images.githubusercontent.com/16898465/60751879-f8b32180-9fef-11e9-9b6d-bf01649a6169.png)

[fillBuffer.patch.txt](https://github.com/Meituan-Dianping/Leaf/files/3364425/fillBuffer.patch.txt)

**Comment by Yaccc** [comment]
这里是因为下一个号段的buffer size也没办法满足堆积的请求下 剩余的请求都会走到com/sankuai/inf/leaf/segment/SegmentIDGenImpl.java:241
，这属于正常设计，可以尝试根据QPS 提高buffer的size大小，目前leaf也会自动根据请求来扩容buffer，或者在这一块主动加一个扩容的逻辑可解
