### ISSUE TITLE
segment模式每分钟更新疑惑

### ISSUE THREAD

**Issue by yanghyu** [Meituan-Dianping/Leaf#49]
我看到segment模式下每分钟都更新了cache，但在updateSegmentFromDb方法中duration与SEGMENT_DURATION比较时的SEGMENT_DURATION是十五分钟，这个怎么解释。duration在这里不可能大于1分钟。肯定是小于15分钟的。

**Comment by thelight1** [comment]
两个更新操作的作用是不一样的。
1）updateCacheFromDb是当db中删除了tag记录或添加了tag记录时，与db保持同步
2）updateSegmentFromDb是从DB中load号段

**Comment by yanghyu** [comment]
谢谢！
