### ISSUE TITLE
Snowflake sequence问题

### ISSUE THREAD

**Issue by zhuyou1234** [Meituan-Dianping/Leaf#52]
SnowflakeIDGenImpl 
 //如果是新的ms开始
 sequence = RANDOM.nextInt(100);
random没什么意义，而且这样导致同一时刻tps下降。原本同一时刻tps可能为1024,但是random后可能减少100了。

**Comment by thelight1** [comment]
snowflake算法1ms可生成4096个，换算成QPS是4096000（409万）
一般不会让单台机器抗这么大流量，到这种量级该通过增加机器等手段来解决了。
4096个浪费100个，应该不是太大问题。

而且这样做是有原因的。可以参考下下面文章。
====================================
https://my.oschina.net/yu120/blog/1784809
5.2 大量偶数
产生原因
        根据上述算法可知，在同一毫秒内是通过一个自增序列号进行区分不同ID，当时间跳至下一毫秒时，自增ID就会被重置为0。因此，如果线上的交易并发量不是很大时（即都是夸毫秒产生时），生成的所有ID的尾号基本都是0，即基本都是偶数。如果直接应用该ID来做分库分表，则极有可能出现数据不均匀的情况。
