### ISSUE TITLE
关于workId

### ISSUE THREAD

**Issue by dictionaryshi** [Meituan-Dianping/Leaf#57]
看下了下源码。workId直接取的zk序列号, 如果ZK序列号超过1023， 那岂不是信节点无法加入。是不是需要取摩处理呢， 望解答。

**Comment by cmzdandan** [comment]
我是这样思考的：一般zk集群的机器数都不会很大，所以ZK序列号超过1023的可能性几乎不存在，尤其是线上环境不会存在。zk集群机器数是2n+1，这个n不会取很大的数，大了则会导致zk之间通信、选举效率非常差，一旦选举，zk集群不可用的时间会增加。

**Comment by cmzdandan** [comment]
@dictionaryshi 
我是这样思考的：一般zk集群的机器数都不会很大，所以ZK序列号超过1023的可能性几乎不存在，尤其是线上环境不会存在。zk集群机器数是2n+1，这个n不会取很大的数，大了则会导致zk之间通信、选举效率非常差，一旦选举，zk集群不可用的时间会增加。

**Comment by zztztt** [comment]
> 看下了下源码。workId直接取的zk序列号, 如果ZK序列号超过1023， 那岂不是信节点无法加入。是不是需要取摩处理呢， 望解答。

我们一个Leaf集群的大小不会超过1023的，一般超过10台就会拆分集群了

**Comment by dictionaryshi** [comment]
@zztztt 了解了，感谢解答。
