### ISSUE TITLE
修改下repo的描述以及标签

### ISSUE THREAD

**Issue by Yaccc** [Meituan-Dianping/Leaf#62]
![image](https://user-images.githubusercontent.com/5906306/66026603-c1d7a380-e52b-11e9-9843-28145f56dd07.png)
像下面这样，方便搜索导流，也更正式一点
![image](https://user-images.githubusercontent.com/5906306/66026629-d1ef8300-e52b-11e9-9777-287dd1457368.png)

**Comment by thelight1** [comment]
我这边编辑不了。 @zztztt 你看看你能不

**Comment by zztztt** [comment]
Done
