### ISSUE TITLE
号段模式下，多台leaf取出的ID不能趋势递增？

### ISSUE THREAD

**Issue by qianjin** [Meituan-Dianping/Leaf#64]
我们有个IM场景，需要每个会话都是趋势递增（可以不连续），但现在如果布多个leaf做不到这一点，有没有什么思路，谢谢了。

**Comment by Yaccc** [comment]
你可以在客户端维护一个会话对应的id有序列表

**Comment by wychenlong** [comment]
目前Leaf Server集群模式下，都可以提供发号服务，不能趋势递增

**Comment by thelight1** [comment]
leaf不保证单调递增的。

**Comment by wychenlong** [comment]
leaf 部署多台服务的话，update的时候是不是也有问题，可能会取到重复的号段步长

**Comment by thelight1** [comment]
> leaf 部署多台服务的话，update的时候是不是也有问题，可能会取到重复的号段步长

leaf扩展性良好，支持水平扩展，而是保证生成的id唯一是最最基本的要求，不会下发重复的id。
具体怎么实现的，可以看首页的介绍leaf如何实现的那篇文章。

**Comment by wychenlong** [comment]
从官方下载的DEM，这边做了并发测试，号段发号器，发现一个问题，就是第一次提交10000个任务，停服务，下次重启 还是从0开始

**Comment by thelight1** [comment]
> 从官方下载的DEM，这边做了并发测试，号段发号器，发现一个问题，就是第一次提交10000个任务，停服务，下次重启 还是从0开始

是说启动leaf-server，id初始值为0，获取10000个id，然后重新启动leaf-server，然后获取id从0开始？消耗号段会更新DB中max_id字段的，重启会不会继续从0开始的。

**Comment by wychenlong** [comment]
号段模式，不能固定长度，有没有什么好的解决方案呢？

**Comment by thelight1** [comment]
> 号段模式，不能固定长度，有没有什么好的解决方案呢？

不能固定长度是指关闭动态调整step？麻烦描述清楚些

**Comment by songzhi** [comment]
> 我们有个IM场景，需要每个会话都是趋势递增（可以不连续），但现在如果布多个leaf做不到这一点，有没有什么思路，谢谢了。
@qianjin 我不懂leaf集群怎么搭的，但是可不可以根据会话ID哈希之后或者别的方法将单个会话的所有请求导向单个主机？类似于负载均衡。
