### ISSUE TITLE
leaf-code里建立zookeeper没有读到配置文件的端口？

### ISSUE THREAD

**Issue by hzjhjjyy** [Meituan-Dianping/Leaf#67]
![QQ图片20191109223217](https://user-images.githubusercontent.com/57552918/68530172-ffa4c480-0340-11ea-92f7-f33b351f9cc5.png)

蓝框里是原有代码用的参数 connectionString，只是个ip。后来改了zoo的端口，连不上zoo了，日志里显示用的还是默认的2181。看了下代码发现没有使用到配置的端口，改成用红框里的参数 listenAddress 才可以。

**Comment by thelight1** [comment]
connectionString并不是ip，具体参考下面
https://stackoverflow.com/questions/30134447/what-does-an-apache-curator-connection-string-look-like
