### ISSUE TITLE
性能小优化建议

### ISSUE THREAD

**Issue by songzhi** [Meituan-Dianping/Leaf#68]
https://github.com/Meituan-Dianping/Leaf/blob/76301dcb45bcbcc594f55ece6b1c0a01886edf84/leaf-core/src/main/java/com/sankuai/inf/leaf/segment/SegmentIDGenImpl.java#L91-L115

这里的insertTags可以直接利用hashmap筛选出来，即判断tag是否在hashmap中，这样复杂度为O（dbTags长度）。而不是使用列表的removeAll方法，这样的话复杂度为O（nm）。

虽然可能性能提升不大，但是改一下也只需要几分钟。

**Comment by thelight1** [comment]
👍虽然是小的改进，欢迎PR
