### ISSUE TITLE
本地执行的问题

### ISSUE THREAD

**Issue by lqlcy1** [Meituan-Dianping/Leaf#69]
![image](https://user-images.githubusercontent.com/9442911/69861738-ec4ba000-12d3-11ea-9ec1-9638564013a1.png)
本地测了下 这个Param注解执行会报错 去掉就好了

**Comment by lqlcy1** [comment]
@Update("UPDATE leaf_alloc SET max_id = max_id + #{step} WHERE biz_tag = #{key}")
    void updateMaxIdByCustomStep(@Param("leafAlloc") LeafAlloc leafAlloc);

@Param("leafAlloc")去掉

**Comment by thelight1** [comment]
检查下错误日志啥的，看看是不是哪里出了问题
