### ISSUE TITLE
SnowflakeZookeeperHolder#PROP_PATH 错误

### ISSUE THREAD

**Issue by caoenergy** [Meituan-Dianping/Leaf#7]
配置文件路径错误:
修正PROP_PATH :
System.getProperty("java.io.tmpdir") => System.getProperty("java.io.tmpdir")  + File.separator

**Comment by zztztt** [comment]
> 配置文件路径错误:
> 修正PROP_PATH :
> System.getProperty("java.io.tmpdir") => System.getProperty("java.io.tmpdir") + File.separator
java.io.tmpdir 默认会携带文件分隔符，是为了避免其他人覆盖？

**Comment by zztztt** [comment]
1426be359ab139e631731b049698861ccd66ee5d fix

**Comment by caoenergy** [comment]
在linux下临时目录为/tmp后面不带/，所以生成不了配置文件

在 2019-03-12 18:23:30，"张志桐" <notifications@github.com> 写道：


配置文件路径错误:
修正PROP_PATH :
System.getProperty("java.io.tmpdir") => System.getProperty("java.io.tmpdir") + File.separator
java.io.tmpdir 默认会携带文件分隔符，是为了避免其他人覆盖？
