### ISSUE TITLE
leaf_name携带 - 导致获取workerId报错

### ISSUE THREAD

**Issue by wuweishuo** [Meituan-Dianping/Leaf#74]
https://github.com/Meituan-Dianping/Leaf/blob/76301dcb45bcbcc594f55ece6b1c0a01886edf84/leaf-core/src/main/java/com/sankuai/inf/leaf/snowflake/SnowflakeZookeeperHolder.java#L85-L92

workerID = Integer.parseInt(nodeKey[1]); 获取到的为leaf_name的值
改为workerID = Integer.parseInt(nodeKey[nodeKey.length - 1]);

**Comment by Issocala** [comment]
这里的nodeMap里面的数据格式类似于192.168.2.116:2184-0000000001，直接nodeKey[1]就已经获取到workerID了，leaf_name在snowflake节点下，所以并不会有问题。

**Comment by shuo123** [comment]
String newNode = createNode(curator);  返回的是全路径而不是节点名

**Comment by Issocala** [comment]
让我们将目光移至String[] nodeKey = newNode.split("-")这行，你会发现是的，workerID = Integer.parseInt(nodeKey[1]); 仍然在获取workerID。当然我们可以说改为nodeKey[nodeKey.length - 1]更为严谨。不过至少原来的设计并不会有什么问题。
