### ISSUE TITLE
关于snowflake模式下需要输入一个字符串的疑问

### ISSUE THREAD

**Issue by Issocala** [Meituan-Dianping/Leaf#75]
snowflake模式下获取id需要输入一个毫无用处的字符串，给我的感觉怪怪的。这里这么处理感觉没有意义的，完全可以写两个接口，匹配不同的模式。是不是因为开源版本为了方便？想问一下大佬。
我这边在实现rpc调用方式，所以觉得可以新建一个模块一些api放入这个模块就可以啦，新建两个接口，snowflake模式获取就不需要输入没有意义的一个字符串了。

**Comment by thelight1** [comment]
1.美团内部使用leaf时，是需要先申请tag的，然后才能使用的。
2.传入tag的作用，审计日志，记录哪些tag调用过，甚至后续可以统计每个tag的调用量。

**Comment by thelight1** [comment]
美团内部使用时，号段模式和snowflake模式，都是要先申请才能使用的，这部分逻辑没有开源出来。

**Comment by Issocala** [comment]
明白了，非常感谢。
