### ISSUE TITLE
Leaf双Buffer优化：加锁有问题，可能出现多次更新号段

### ISSUE THREAD

**Issue by lemonlee** [Meituan-Dianping/Leaf#76]
下面代码是截取双Buffer方案里更新号段的实现代码：
public Result getIdFromSegmentBuffer(final SegmentBuffer buffer) {
        while (true) {
            buffer.rLock().lock();
            try {
                final Segment segment = buffer.getCurrent();
                if (!buffer.isNextReady() && (segment.getIdle() < 0.9 * segment.getStep()) && buffer.getThreadRunning().compareAndSet(false, true)) {
                    service.execute(new Runnable() {
                        @Override
                        public void run() {}
          }

上面这段代码的if 判断，在如下场景会有问题：
 1. 如果两个线程a，b同时开始执行if 语句，都执行完第一个条件，且都成立（认为下一个号段未准备好）。
 2. 线程a 执行完if 语句，条件成立，提交了更新号段的任务。
 3. 线程a提交的号段更新任务执行完成。
 4. 线程b 继续执行if 语句里剩下的两个条件，且都成立,又提交了一个更新号段的任务。

上述场景就出现了提交两次号段更新任务
这种多次更新号段的场景是不是可能出现？求大佬解答一下。

**Comment by Issocala** [comment]
buffer.getThreadRunning().compareAndSet(false, true) 这里用了cas的形式保证。
