### ISSUE TITLE
如何解决segment浪费严重的问题？

### ISSUE THREAD

**Issue by zacharyzhu096** [Meituan-Dianping/Leaf#78]
有这样一个场景：leaf服务运行一段时间，流量较大，此时的步长很长（假如一直维持在MAX_STEP,即10万）。当某时刻current segment的数据消费10%，系统会异步准备next segment。当current segment消费了10.01%数据时，此时leaf服务挂了。然后又重启服务。你会发现segment浪费很严重。如何去解决这个问题？

**Comment by Issocala** [comment]
> 有这样一个场景：leaf服务运行一段时间，流量较大，此时的步长很长（假如一直维持在MAX_STEP,即10万）。当某时刻current segment的数据消费10%，系统会异步准备next segment。当current segment消费了10.01%数据时，此时leaf服务挂了。然后又重启服务。你会发现segment浪费很严重。如何去解决这个问题？

这是个开源的，你完全可以根据自己也需求来进行定制化开发。比如：你可以将10%改为其他的，代码中是90%比较。

**Comment by zacharyzhu096** [comment]
恩，如果把10%这个值改成90%的话，segment的浪费就没有那么严重。

**Comment by Issocala** [comment]
> 恩，如果把10%这个值改成90%的话，segment的浪费就没有那么严重。

对的，但是这样的话，流量太快的话会有性能问题，不过我们需要自己看需求。

**Comment by zacharyzhu096** [comment]
考虑到step是动态的。我觉得表leaf_alloc中应加上一个字段value来记录，当前segment的初值。每次服务关闭之前，要记录一下最大的id的值（设为id_last_used）。然后，重启服务之后，用id_last_used去比较value的值，如果比它小，那么就不需要将max_id的值置为max_id + step。这种做法可以节省segment。如果id_last_used >value，那么就执行max_id = max_id + step；

**Comment by Issocala** [comment]
> 考虑到step是动态的。我觉得表leaf_alloc中应加上一个字段value来记录，当前segment的初值。每次服务关闭之前，要记录一下最大的id的值（设为id_last_used）。然后，重启服务之后，用id_last_used去比较value的值，如果比它小，那么就不需要将max_id的值置为max_id + step。这种做法可以节省segment。如果id_last_used >value，那么就执行max_id = max_id + step；

你考虑一下你如果能够服务宕机的时候记录当前id，那么还需要每次从最大出发吗？

**Comment by zacharyzhu096** [comment]
的确比较鸡肋，如果10%调整到90%的话，当db不可用时，当此时流量比较大的时，剩余的id很快就会消费完的。

**Comment by zacharyzhu096** [comment]
哦，我明白你的意思啦。我考虑的不周到。

**Comment by Issocala** [comment]
> 哦，我明白你的意思啦。我考虑的不周到。

可以一起交流，有兴趣可以加我

**Comment by zacharyzhu096** [comment]
恩，有没有交流群？

**Comment by Issocala** [comment]
> 恩，有没有交流群？

好像美团管理员回复说稍后创建，就没有然后了。

**Comment by Issocala** [comment]
> 恩，有没有交流群？

834704671加我qq吧

**Comment by zacharyzhu096** [comment]
这个项目应该不是美团官方维护的吧？看了5天的源码，我的强迫症快犯了。有些变量和方法的命名还是大写的。IDAllocMapper对应实体是LeafAlloc，我有些看不习惯。。。晕死

**Comment by Issocala** [comment]
> 这个项目应该不是美团官方维护的吧？看了5天的源码，我的强迫症快犯了。有些变量和方法的命名还是大写的。IDAllocMapper对应实体是LeafAlloc，我有些看不习惯。。。晕死

我也不太清楚，只能说有人负责解答吧。

**Comment by leechliao** [comment]
> 考虑到step是动态的。我觉得表leaf_alloc中应加上一个字段value来记录，当前segment的初值。每次服务关闭之前，要记录一下最大的id的值（设为id_last_used）。然后，重启服务之后，用id_last_used去比较value的值，如果比它小，那么就不需要将max_id的值置为max_id + step。这种做法可以节省segment。如果id_last_used >value，那么就执行max_id = max_id + step；

是一个节约的好思路
