### ISSUE TITLE
leaf集群生产自增ID疑惑？

### ISSUE THREAD

**Issue by wealthtears** [Meituan-Dianping/Leaf#79]
如果leaf集群有俩台服务器，第一台号段是1-1000，第二台是1001-2000。获取id的时候第一次从第二台服务器获取，下一次从第一台服务器获取，那么id是不是就不是递增了。

**Comment by Yaccc** [comment]
> 如果leaf集群有俩台服务器，第一台号段是1-1000，第二台是1001-2000。获取id的时候第一次从第二台服务器获取，下一次从第一台服务器获取，那么id是不是就不是递增了。

是的，所有leaf是趋势递增，不是绝对递增
