### ISSUE TITLE
目前支持高可用部署吗

### ISSUE THREAD

**Issue by jaychang9** [Meituan-Dianping/Leaf#8]
我想问下目前是否支持高可用部署

**Comment by zztztt** [comment]
可以多机器部署，不过不能保证ID严格自增。

**Comment by liangyanfeng** [comment]
号段模式下， 如果多机部署的话，应该会产生 相同的 ID 吧

**Comment by mawenjian** [comment]
> 号段模式下， 如果多机部署的话，应该会产生 相同的 ID 吧

不会的，不同机器用的是不同的号段。源码就那么点，读一读就明白了。
