### ISSUE TITLE
文档写的挺好的，但是能再更详细点就更好了

### ISSUE THREAD

**Issue by 01jiagnwei01** [Meituan-Dianping/Leaf#81]
我按照文档的说明，进行了如下修改：
`
leaf.snowflake.enable=true

leaf.snowflake.zk.address=127.0.0.1:2181

leaf.snowflake.port=8988
`
然后我启动了项目：mvn spring-boot:run

**结果是**：我余下的工作不知道该怎么做了，我也不知道我获得了什么，我怎么能获得订单号，怎么维护。

**我进行了如下操作：**
1：http://localhost:8080/cache 
 1.1.1 结果报错，看异常，说明是支持号段模式。
**我建议：**
  1：将文档在现有基础上在补充下，如何操作，获得了什么。还有哪些补充方案等。

**Comment by Issocala** [comment]
我个人认为如果你想要入手这个id服务还是需要有一定的开发能力的，文档的确也可以详细一点，给一些初学者。没有接触过这些东西的，不过你没有接触过的话，需要的应该是更需要有zk的基础吧。因为这个应该是内部提取一些拿出来开源的，所以有些做法我也不是很理解。不过还好有大佬解答！

**Comment by Yaccc** [comment]
欢迎补充
