### ISSUE TITLE
leaf多台机器部署时候,cache不能共享，美团内部有什么好的解决方案吗？cache存到redis可行不？

### ISSUE THREAD

**Issue by yangchangjiang** [Meituan-Dianping/Leaf#91]
现象描述：
为防止单台leaf-server出现故障。将leaf-server 多机器注册到注册中心后，例如spring cloud的eureka注册中心，然后对外提供服务。会出现id跳动生成，不连续。
例如在step为2000的情况下，id从1开始，如果启动三台机器：A机器1-2000 B机器 2001-4000 C机器4001-6000 则ID生成会呈现
1 2001 4001 2 2002 4002 3 2003 4003的现象

能不能把cache存放在redis里呢？效率会有影响吗？还是说做HA，保证一台挂了，另外一台马上起来。永远只要一台提供服务？

**Comment by thelight1** [comment]
leaf本来就不知道单调递增的。

**Comment by thelight1** [comment]
https://github.com/Meituan-Dianping/Leaf/issues/82 可参考这个下面的解答
