### ISSUE TITLE
请问，SnowflakeIDGenImpl中的twepoch属性有意义吗？

### ISSUE THREAD

**Issue by hxpeng123** [Meituan-Dianping/Leaf#93]
请问，SnowflakeIDGenImpl在最后进行位运算的时候，为什么要用当前的时间戳 减去 twepoch再进行运算呢。。。

不好意思，笨拙没看懂

**Comment by NotFound9** [comment]
时间戳是当前时间减去1970年1月1号的时间差，如果自定义起始时间点twepoch，使用当前时间减去twepoch作为时间差，在对时间部分分配相同的位数下，支持的最大时间会更大。

**Comment by hxpeng123** [comment]
那把自定义起始时间设置为 2020年4月12号，那按你的意思，当前时间（四月13号），那么时间差就是一天的毫秒数，
甚至，我自定义其起始时间设置与当前时间相差一毫秒，那是不是支持的最大时间为最大了？
感觉没多大意义呀
还是我理解错你意思了

**Comment by hxpeng123** [comment]
> 时间戳是当前时间减去1970年1月1号的时间差，如果自定义起始时间点twepoch，使用当前时间减去twepoch作为时间差，在对时间部分分配相同的位数下，支持的最大时间会更大。

那把自定义起始时间设置为 2020年4月12号，那按你的意思，当前时间（四月13号），那么时间差就是一天的毫秒数，
甚至，我自定义其起始时间设置与当前时间相差一毫秒，那是不是支持的最大时间为最大了？
感觉没多大意义呀
还是我理解错你意思了

**Comment by hxpeng123** [comment]
明白鸟，谢谢老哥
